### PR TITLE
Added: Dependabot & updated circleci orb

### PR DESCRIPTION
**Pull request by GoliathLabs**
Hi,
I've added a proper dependabot.yml config and updated the circleci orb in the .circleci directory.

Feel free to leave some feedback 😄

### CODE REVIEW

**Review by itzg — APPROVED** [review]
Thank you; however, heads up that I am gradually switching my projects to GitHub actions. I hadn't needed to make a change to easy-add in quite a while, so I do appreciate the dependabot part to keep things fresh.

**Comment by GoliathLabs** [comment]
Oh well. Then the Circle-Ci change was probably not so necessary after all :P

But at least dependabot has opened a new PR for a Go module.

**Comment by itzg** [comment]
Yep, it's all good. The build is failing I'm guessing because the GitHub token is expired 😬 Now I have the motivation to get this project freshened up over in GitHub actions.

**Comment by GoliathLabs** [comment]
You may also want to take a look at the new Github tokens (they were introduced some time ago) as well as the repository-specific tokens (which may do the trick here).

**Comment by itzg** [comment]
Yep, I know. That's what it's needing.

**Pull request merged**
